RUN = g++ checker.cpp -o test -lcurl -lessentials -lpath -lchecksum -lws2_32 -std=c++17 -I"G:/msys2/mingw64/include" -L"G:\msys2\mingw64\lib" -L.
TARGET = test.cpp


all: $(TARGET)

$(TARGET):
	$(RUN)


